Repository cupofdata/cupofdata.com, pull requests merged in 2018-04, with the labels that each got.

#237 CMS updates for home banner
  content/home-banner/banner.md
  src/components/Home/BannerSection.js
  src/pages/index.js
  src/templates/banner.js
  static/admin/config.yml
Labels: feature

#241 Change free trial text
  src/components/Pricing/PriceSection.js
Labels: chore

#243 Convert png's
  static/files/images/ashley.png
  static/files/images/avatar-anna.png
  static/files/images/bk-automarketing.png
  static/files/images/bk-news.png
  static/files/images/greg.png
  static/files/images/john.png
  static/files/images/josh.png
  static/files/images/mike.png
  static/files/images/nathaniel.png
  static/files/images/timara.png
  static/files/images/tj_bramblett.png
Labels: chore

#246 Remove disqus references
  gatsby-config.js
  src/templates/blog.js
Labels: chore

#247 Add tags feature
  content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
  content/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
  content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
  content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
  gatsby-node.js
  src/components/BlogCard.js
  src/pages/blog.js
  src/templates/tag.js
  static/admin/config.yml
Labels: feature, netlify cms

#249 updated styles
  src/components/Layout.js
  src/styles/global.js
Labels: blog, design update

#252 Font styles
  src/components/Contact.js
  src/components/Home/AutomatedMarketing.js
  src/components/Home/BannerSection.js
  src/components/Home/Benefits.js
  src/components/Home/Features.js
  src/components/Home/HowItWorks.js
  src/components/Home/News.js
  src/components/Navbar.js
  src/components/PriceCard.js
  src/components/Pricing/FAQ.js
  src/components/Pricing/PriceSection.js
  src/components/Typography.js
  src/layouts/index.js
  src/styles/global.js
  src/styles/theme.js
  src/templates/about.js
Labels: chore

#251 Update site elements to modify contact section with CMS
  content/contact/mission.md
  src/components/Contact.js
  src/components/Home/BannerSection.js
  src/components/Home/Features.js
  src/components/Home/News.js
  src/layouts/index.js
  src/pages/blog.js
  src/pages/index.js
  src/templates/contact.js
  static/admin/config.yml
Labels: feature

#254 Update pricing with CMS
  static/admin/config.yml
Labels: netlify cms

#259 Update automated marketing section with CMS
  content/automatedmarketing/let-us-help-you-get-started-on-us.md
  src/components/Home/AutomatedMarketing.js
  src/components/Layout.js
  src/pages/index.js
  src/templates/automatedmarketing.js
  static/admin/config.yml
Labels: feature, netlify cms

#262 Update about link
  src/components/Contact.js
Labels: bug

#264 Enable editorial workflow
  static/admin/config.yml
Labels: chore

#271 License and readme update
  LICENSE.md
  README.md
Labels: chore

#274 Git backend
  static/admin/config.yml
Labels: chore

#281 Remove alpha from pngs
  static/files/images/ashley.png
  static/files/images/avatar-anna.png
  static/files/images/greg.png
  static/files/images/john.png
  static/files/images/josh.png
  static/files/images/mike.png
  static/files/images/nathaniel.png
  static/files/images/timara.png
  static/files/images/tj_bramblett.png
Labels: chore

#288 Reduce image size
  static/files/images/ashley.png
  static/files/images/avatar-anna.png
  static/files/images/greg.png
  static/files/images/john.png
  static/files/images/josh.png
  static/files/images/mike.png
  static/files/images/nathaniel.png
  static/files/images/timara.png
  static/files/images/tj_bramblett.png
Labels: chore

#294 Initial ESLint config
  .eslintrc
  gatsby-config.js
  package-lock.json
  package.json
  yarn.lock
Labels: chore

#297 Style updates
  .eslintrc
  README.md
  package.json
  src/components/About.js
  src/components/AvatarCard.js
  src/components/BlogCard.js
  src/components/Contact.js
  src/components/Footer.js
  src/components/Home/AutomatedMarketing.js
  src/components/Home/BannerSection.js
  src/components/Home/Benefits.js
  src/components/Home/Features.js
  src/components/Home/HowItWorks.js
  src/components/Home/News.js
  src/components/Home/Testimonials.js
  src/components/Navbar.js
  src/components/PriceCard.js
  src/components/Pricing/FAQ.js
  src/components/Pricing/PriceSection.js
  src/components/Typography.js
  src/layouts/index.js
  src/pages/404.js
  src/pages/blog.js
  src/pages/index.js
  src/pages/pricing.js
  src/styles/theme.js
  src/templates/about.js
  src/templates/automatedmarketing.js
  src/templates/banner.js
  src/templates/blog.js
  src/templates/contact.js
  src/templates/faq.js
  src/templates/feature.js
  src/templates/legal.js
  src/templates/pricing.js
  src/templates/tag.js
  src/templates/testimonial.js
  static/files/images/ashley.png
  yarn.lock
Labels: chore
