Repository cupofdata/cupofdata.com, pull requests merged in 2018-02, with the labels that each got.

#59 Dropdown navbar responsive
  src/containers/Navbar/index.js
Labels: feature

#68 Favicon
  src/favicon.png
  src/html.js
Labels: feature

#91 update company profile page
  src/layouts/index.js
  src/templates/about.js
Labels: design update, feature

#92 Update deployment branch
  gatsby-config.js
  package.json
  src/containers/BannerSection/index.js
  src/containers/Navbar/index.js
  src/layouts/index.js
  src/pages/blog.js
  src/pages/index.js
  src/pages/legal/privacy_policy.md
  src/pages/legal/terms_and_conditions.md
  src/pages/onboard.js
  src/styles/global.js
  src/templates/about.js
  src/templates/blog.js
  src/templates/legal.js
  static/admin/config.yml
Labels: chore

#99 Fix blog typo
  src/containers/Contact/index.js
  src/pages/blog.js
Labels: bug, design fix

#107 Fix A.I.. typos
  src/containers/Contact/index.js
  src/pages/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
Labels: bug

#106 Update pricing page texts
  src/containers/Pricing/FAQ/index.js
  src/containers/Pricing/PriceSection/index.js
Labels: chore

#139 [WIP] Update website banner
  src/components/Typography.js
  src/containers/Home/BannerSection/index.js
  src/layouts/index.js
  static/files/images/background.svg
  static/files/images/img-person1.svg
  static/files/images/img-person2.svg
  static/files/images/img-person3.svg
  static/files/images/img-person4.svg
Labels: design update

#134 Fix favicon
  gatsby-config.js
  package.json
  src/html.js
Labels: bug

#143 mobile responsive for banner section
  src/components/Button.js
  src/containers/Home/BannerSection/index.js
  static/files/images/mobile-background.svg
Labels: design update

#145 Clean up repo files
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE
  README.md
  package-lock.json
  package.json
  src/containers/Home/BannerSection/index.js
  src/layouts/index.js
  src/styles/global.js
Labels: chore
