Repository cupofdata/cupofdata.com, pull requests merged in 2018-03, with the labels that each got.

#168 Update admin
  content/about/about.md
  content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
  content/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
  content/blog/2018-02-08-ai-models-for-marketers-and-flight-simulators.md
  content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
  content/faq/2018-02-17-do-you-augment-account-and-contact-lists-with-context.md
  content/faq/2018-02-17-do-you-integrate-with-crm-and-martech-solutions.md
  content/faq/2018-02-17-do-you-leverage-third-party-databases.md
  content/faq/2018-02-17-do-you-offer-free-trials-for-your-services.md
  content/faq/2018-02-17-how-is-your-service-different-from-all-other-b2b-lead-gen-services-out-there.md
  content/faq/2018-02-17-what-forms-of-payment-do-you-accept.md
  content/legal/privacy_policy.md
  content/legal/terms_and_conditions.md
  content/testimonials/anna-anisin.md
  content/testimonials/robert-joseph.md
  gatsby-config.js
  package-lock.json
  package.json
  static/_redirects
  static/admin/config.yml
  static/admin/index.html
  static/admin/netlify_redirect.js
Labels: chore

#171 add profile pics and ref
  content/about/about.md
  static/files/blog/ashley.png
  static/files/blog/timara.png
Labels: feature

#172 update banner text
  src/containers/Home/BannerSection/index.js
Labels: design update

#175 update testimonial to tj
  content/testimonials/robert-joseph.md
  content/testimonials/tj_bramblett.md
  static/files/blog/tj_bramblett.png
Labels: design update

#178 Converted fake links to proper link tags
  src/components/PriceCard.js
  src/containers/Home/News/index.js
  src/containers/Navbar/index.js
  src/pages/blog.js
Labels: chore

#181 Add article and image for understanding the problem post
  content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
  static/files/blog/don_datanerd.gif
Labels: feature

#183 Fix published date
  content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
Labels: bug

#185 Banner main text update
  src/containers/Home/BannerSection/index.js
Labels: design update

#187 Update prices
  src/containers/Pricing/PriceSection/index.js
Labels: chore

#189 Fix annual typo
  src/containers/Pricing/PriceSection/index.js
Labels: bug

#192 add blog to relative path
  content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
  content/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
  content/blog/2018-02-08-ai-models-for-marketers-and-flight-simulators.md
  content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
  content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
Labels: feature

#195 Update mission statement
  src/containers/Contact/index.js
Labels: design update

#198 Remove disqus from blog entries
  src/templates/blog.js
Labels: chore

#202 Mobile background image
  src/components/Home/BannerSection.js
  static/files/images/mobile-background_blue.svg
Labels: design update

#199 Blog entry updates
  content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
  content/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
  content/blog/2018-02-08-ai-models-for-marketers-and-flight-simulators.md
  content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
  content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
  content/blog/2018-03-16-things-to-consider-when-b2b-prospecting.md
  static/admin/config.yml
  static/files/images/ashley.png
  static/files/images/avatar-anna.png
  static/files/images/avatar-robert.png
  static/files/images/don_datanerd.gif
  static/files/images/file_manager.gif
  static/files/images/filght_sim.jpg
  static/files/images/flip-my-funnel.jpg
  static/files/images/greg.png
  static/files/images/john.png
  static/files/images/josh.png
  static/files/images/launch.jpg
  static/files/images/me1 sm.jpeg
  static/files/images/mike.png
  static/files/images/nathaniel.png
  static/files/images/process.gif
  static/files/images/process_chart.gif
  static/files/images/ray.png
  static/files/images/res2.jpg
  static/files/images/timara.png
  static/files/images/tj_bramblett.png
Labels: chore

#205 Profile update
  content/about/about.md
  static/files/images/ray.png
Labels: design update

#207 Move images to files -> images
  content/about/about.md
Labels: chore

#211 force 1.3.5 with resolution
  package-lock.json
  package.json
Labels: bug

#212 Add yarn.lock
  .gitignore
  package.json
  yarn.lock
Labels: bug

#214 Image fix
  content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
  static/files/images/res1.jpg
Labels: bug

#218 Fix testimonial paths
  content/testimonials/anna-anisin.md
  content/testimonials/tj_bramblett.md
Labels: bug

#224 Add page title to 404 for tracking
  gatsby-config.js
  package-lock.json
  package.json
  src/pages/404.js
Labels: feature

#226 Segment fix
  gatsby-config.js
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#227 Image fix
  gatsby-config.js
  src/components/AvatarCard.js
  src/components/Contact.js
  src/components/Home/AutomatedMarketing.js
  src/components/Home/BannerSection.js
  src/components/Home/Benefits.js
  src/components/Home/Features.js
  src/components/Home/News.js
  src/components/Navbar.js
  src/components/PriceCard.js
  src/img/background.svg
  src/img/bk-404.svg
  src/img/bk-automarketing.png
  src/img/bk-news.png
  src/img/bk-slick1.svg
  src/img/bk-slick2.svg
  src/img/don_datanerd.gif
  src/img/file_manager.gif
  src/img/filght_sim.jpg
  src/img/flip-my-funnel.jpg
  src/img/img-404.svg
  src/img/img-backborder.svg
  src/img/img-clear-path.svg
  src/img/img-desktop.png
  src/img/img-desktop@2x.png
  src/img/img-enterprise.svg
  src/img/img-existing.svg
  src/img/img-left.svg
  src/img/img-logo-dark.svg
  src/img/img-logo.svg
  src/img/img-person1.svg
  src/img/img-person2.svg
  src/img/img-person3.svg
  src/img/img-person4.svg
  src/img/img-quote.svg
  src/img/img-right.svg
  src/img/img-sales.svg
  src/img/img-shorten-sales.svg
  src/img/img-slick1.svg
  src/img/img-slick2.svg
  src/img/launch.jpg
  src/img/mobile-background.svg
  src/img/mobile-background_blue.svg
  src/pages/404.js
  src/pages/index.js
  static/admin/config.yml
  static/files/images/avatar-anna.png
  static/files/images/avatar-robert.png
Labels: feature
